entity.announcement.canonical:
  route_name: entity.announcement.canonical
  base_route: entity.announcement.canonical
  title: 'View'

entity.announcement.edit_form:
  route_name: entity.announcement.edit_form
  base_route: entity.announcement.canonical
  title: Edit

entity.announcement.delete_form:
  route_name:  entity.announcement.delete_form
  base_route:  entity.announcement.canonical
  title: Delete
  weight: 10